### PR TITLE
ERRDEF/ERRNDEF custom text display issue fix

### PR DESCRIPTION
**Pull request by sergstetsuk**
https://github.com/JWasm/JWasm/issues/184 fix. Don't know though if it will crash when no text is specified. I have no crashes under Linux.

### CODE REVIEW

**Comment by milabs** [comment]
It still doesn't work as expected. See the example:

~~~
bash-3.2$ cat test.asm
.386
.model flat,stdcall
option casemap:none
.errndef Unicode, Unicode is not defined...
.code
start:
ret
end start
bash-3.2$ ~/projects/JWasm/GccUnixR/jwasm test.asm
JWasm v2.12pre, Mar  3 2017, Masm-compatible assembler.
Portions Copyright (c) 1992-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.

test.asm(4) : Error A2209: Syntax error: is not defined...
test.asm: 8 lines, 1 passes, 200 ms, 0 warnings, 1 errors
bash-3.2$
~~~

As per MASM [documentation](https://msdn.microsoft.com/en-us/en-en/library/08cssy16.aspx) the syntax is:

`.ERRNDEF name [[, message]]`

So, the message may consists of more than one word.

And the last one. Try to fix `.errndef Unicode` also, i.e. without the message string.

Kindly

**Comment by sergstetsuk** [comment]
Message is param. So try <multi word msg with spaces in braces>

**Comment by milabs** [comment]
Ok, I see. It works, but there is still incorrect result if the message was missed. Also, consider to add a test for that issue?

**Comment by sergstetsuk** [comment]
I think now it will work without message too. Don't know where to add tests.

[test.asm.txt](https://github.com/JWasm/JWasm/files/818856/test.asm.txt)

**Comment by sergstetsuk** [comment]
rebase over upstream/master

**Comment by milabs** [comment]
Commited as 9f257e0b33fb2e23a051b0527c1ea0cd3a2d31b1. Note that the #184 issue was fixed, but it's not compatible with MASM because for some reasons MASM ignores `[[, message]]` part.

**Pull request closed without merging**
